maxFramesDisappeared=22
minContourArea=9
maxRectCircumference=237
maxVerticalDisplacementPixels=4403
minHorizontalMovementPixels=-1
maxAssociationDistancePixels=114
mog2HistoryFrames=7299
mog2VarThreshold=174
mog2DetectShadows=true
morphologyKernelSize=5
morphologyOpenIterations=0
morphologyDilateIterations=0
normalizedMaskThreshold=242
